from mainWindow import MainWindow

if __name__ == '__main__':
    mainWindow = MainWindow(height=720, width=1280)

    mainWindow.add_node_to_tier(1, "testoooooooooooooooooooooooooooooooooooooooooooooooooooooooo")
    mainWindow.add_node_to_tier(2, "sest")
    mainWindow.add_node_to_tier(2, "sest")
    mainWindow.add_node_to_tier(3, "sadadasadsdaw")
    mainWindow.add_node_to_tier(4, "papyyzyzyzyyzyz")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "3")
    # mainWindow.add_node_to_tier(5, "4")
    # mainWindow.add_node_to_tier(5, "5")
    # mainWindow.add_node_to_tier(5, "6")
    # mainWindow.add_node_to_tier(5, "7")
    # mainWindow.add_node_to_tier(5, "8")
    # mainWindow.add_node_to_tier(5, "9")
    # mainWindow.add_node_to_tier(5, "10")
    # mainWindow.add_node_to_tier(5, "1")
    # mainWindow.add_node_to_tier(5, "2")
    # mainWindow.add_node_to_tier(5, "3")
    # mainWindow.add_node_to_tier(5, "4")
    # mainWindow.add_node_to_tier(5, "5")
    # mainWindow.add_node_to_tier(5, "6")
    # mainWindow.add_node_to_tier(5, "7")
    # mainWindow.add_node_to_tier(5, "8")
    # mainWindow.add_node_to_tier(5, "9")
    # mainWindow.add_node_to_tier(5, "last")



    mainWindow.run()